"""Config related tables

Revision ID: 65c962c58b8d
Revises: 1fe881c343cf
Create Date: 2026-01-05 21:47:46.369042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65c962c58b8d'
down_revision = '1fe881c343cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_config_provider'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_config_provider'), ['provider'], unique=False)

    # ### end Alembic commands ###
