"""Fix index

Revision ID: 67c2cc56fd97
Revises: 65c962c58b8d
Create Date: 2026-01-06 23:00:35.993339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67c2cc56fd97'
down_revision = '65c962c58b8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('idx_messages_session_id_timestamp', ['session_id', 'timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('idx_messages_session_id_timestamp')

    # ### end Alembic commands ###
